# - Find gdal and gdal dependancies
#
#

IF (GDAL_INCLUDE_DIR)
  # Already in cache, be silent
  SET(GDAL_FIND_QUIETLY TRUE)
ENDIF (GDAL_INCLUDE_DIR)

FIND_PATH(GDAL_INCLUDE_DIR gdal.h)
FIND_LIBRARY(GDAL_LIBRARY NAMES gdal )

# handle the QUIETLY and REQUIRED arguments and set GDAL_FOUND to TRUE if
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GDAL DEFAULT_MSG GDAL_LIBRARY GDAL_INCLUDE_DIR)

IF(GDAL_FOUND)

  SET( GDAL_LIBRARIES ${GDAL_LIBRARY} )
  SET (GDAL_CONFIG ${CMAKE_INSTALL_PREFIX}/bin/gdal-config CACHE FILEPATH "Path to a program.")

  IF(GDAL_CONFIG)

    EXEC_PROGRAM(${GDAL_CONFIG} ARGS --version OUTPUT_VARIABLE GDAL_VERSION )
    EXEC_PROGRAM(${GDAL_CONFIG} ARGS --prefix  OUTPUT_VARIABLE GDAL_PREFIX )
    EXEC_PROGRAM(${GDAL_CONFIG} ARGS --dep-libs OUTPUT_VARIABLE GDAL_CONFIG_LIBS )

  ENDIF(GDAL_CONFIG)

  IF(GDAL_PREFIX)
    FIND_PATH(GDAL_INCLUDE_DIR gdal.h ${GDAL_PREFIX}/include)
  ENDIF(GDAL_PREFIX)

  STRING(REGEX REPLACE "([0-9]+)\\.([0-9]+)\\.([0-9]+)" "\\1" GDAL_VERSION_MAJOR "${GDAL_VERSION}")
  STRING(REGEX REPLACE "([0-9]+)\\.([0-9]+)\\.([0-9]+)" "\\2" GDAL_VERSION_MINOR "${GDAL_VERSION}")

  STRING(REGEX MATCHALL "[-][L]([^ ;])+" GDAL_LINK_DIRECTORIES_WITH_PREFIX "${GDAL_CONFIG_LIBS}" )
  STRING(REGEX REPLACE "[-][L]" "" GDAL_LINK_DIRECTORIES ${GDAL_LINK_DIRECTORIES_WITH_PREFIX} )
  STRING(REGEX MATCHALL "[-][l]([^ ;])+" GDAL_LIB_NAME_WITH_PREFIX "${GDAL_CONFIG_LIBS}" )
  STRING(REGEX REPLACE "[-][l]" " " GDAL_LIB_NAME ${GDAL_LIB_NAME_WITH_PREFIX} )


  #MESSAGE(STATUS "DBG GDAL_VERSION ${GDAL_VERSION}")
  #MESSAGE(STATUS "DBG GDAL_PREFIX ${GDAL_PREFIX}")
  #MESSAGE(STATUS "DBG GDAL_INCLUDE_DIR ${GDAL_INCLUDE_DIR}")
  #MESSAGE(STATUS "DBG  GDAL_LINK_DIRECTORIES_WITH_PREFIX=${GDAL_LINK_DIRECTORIES_WITH_PREFIX}")
  #MESSAGE(STATUS "DBG  GDAL_LINK_DIRECTORIES=${GDAL_LINK_DIRECTORIES}")
  #MESSAGE(STATUS "DBG  GDAL_LIB_NAME_WITH_PREFIX=${GDAL_LIB_NAME_WITH_PREFIX}")
  #MESSAGE(STATUS "DBG  GDAL_LIB_NAME=${GDAL_LIB_NAME}")

list(APPEND GDAL_LIBRARY ${GDAL_LIB_NAME_WITH_PREFIX} )

ELSE(GDAL_FOUND)
  SET( GDAL_LIBRARIES )

ENDIF(GDAL_FOUND)
